### PR TITLE
Destroy DatabaseHolder on FlowManager.destroy

### PR DESCRIPTION
**Pull request by kaeawc**
The issue behind #251 was that `DatabaseHolder` was not null after calling `FlowManager.destroy`, so if we called `FlowManager.init` at any point after that it would not reinitialize the database.

If needed I can write a test to demonstrate this working correctly.

### CODE REVIEW

**Comment by kaeawc** [comment]
@agrosner Can this issue + fix make it into 2.0.1? Is there anything more I can do to make this PR better?

**Comment by kaeawc** [comment]
@agrosner I created a sample app with screenshots to show how this issue occurs:

https://github.com/kaeawc/dbflow-sample-app

**Comment by agrosner** [comment]
@kaeawc thanks for the help, sorry for the late response. Rather we should just reopen the database inside `reset()` in `BaseDatabaseDefinition`:

Try this:

```
public void reset(Context context) {
        if (!isResetting) {
            isResetting = true;
            context.deleteDatabase(getDatabaseFileName());
            flowSQLiteOpenHelper = new FlowSQLiteOpenHelper(this, internalHelperListener);
            isResetting = false;
            flowSQLiteOpenHelper.getWritableDatabase();
        }
    }

```

And see if that fixes the solution to #251

**Comment by kaeawc** [comment]
@agrosner Sure, will try that out

**Comment by kaeawc** [comment]
@agrosner Seems to silently fail instead of crash. I made the change you suggested locally and then used it like this:

```
String databaseName = getDatabaseName();
BaseDatabaseDefinition definition = FlowManager.getDatabase(databaseName);
definition.reset(context);
```

```
Log.d(TAG, "Creating new Widget");
Widget widget = new Widget();
widget.name = "asdf";
widget.save();

Log.d(TAG, "Updating Widget count");
long count = Widget.getCount();
Log.d(TAG, String.format("Widget count now %s", count));
```

**Comment by kaeawc** [comment]
Using adb I can see it did reinitialize the database correctly, but subsequent attempts to save the Widget model don't make it in.

**Comment by kaeawc** [comment]
@agrosner I merged the latest changes to develop into my branch and added the suggestion you made. It still doesn't work correctly in the case where we attempt to reinitialize the database during the same application / activity lifecycle, so I kept the DatabaseHolder in FlowManager change.

It might be a cleaner API if the `reset()` function in BaseDatabaseDefinition did all of this, but I'm not sure how to go about that.

**Comment by kaeawc** [comment]
I made an experimental branch so you can see something I tried, want to get your opinion on it before I added it to this PR.

I kept the modification to [BaseDatabaseDefinition](https://github.com/kaeawc/DBFlow/blob/experiment/db-destroy-app/DBFlow/src/main/java/com/raizlabs/android/dbflow/config/BaseDatabaseDefinition.java#L214). But I added a call from [FlowManager.destroy()](https://github.com/kaeawc/DBFlow/blob/experiment/db-destroy-app/DBFlow/src/main/java/com/raizlabs/android/dbflow/config/FlowManager.java#L185) to `BaseDatabaseDefinition.reset()` for each database specified. This way the end user can choose to delete some, all, or none of the databases while also ensuring `FlowManager`'s references to databases are properly destroyed. Then on the next `FlowManager.init()` the `DatabaseHolder` value is null and thus will attempt to recreate database(s) if it needs to.

You can see how it works from a sample app [here](https://github.com/kaeawc/DBFlow/blob/experiment/db-destroy-app/app/src/main/java/com/raizlabs/android/dbflow/MainFragment.java#L81)

**Comment by kaeawc** [comment]
@agrosner Anything else I can do to help this PR? I made sure its still good to merge into develop.

**Comment by YSDC** [comment]
Meet the same issue in my tests (not able to run two tests..)

Hope this PR will be accepted soon!

**Comment by kaeawc** [comment]
@agrosner I'm currently using reflection to work around this bug in my app. Could you let me know what prevents this from being merged?

**Comment by kaeawc** [comment]
This is the hack I'm using as a workaround https://github.com/kaeawc/dbflow-sample-app/blob/master/app/src/main/java/io/kaeawc/flow/app/ui/MainActivityFragment.java#L201

```
    private void reflectionHack(@NonNull Context context) {

        try {
            Field field = FlowManager.class.getDeclaredField("mDatabaseHolder");
            setFinalStatic(field, null);
            Timber.v("mDatabaseHolder has been set to null");
        } catch (NoSuchFieldException noSuchField) {
            Timber.d(noSuchField, "No such field exists in FlowManager");
        } catch (IllegalAccessException illegalAccess) {
            Timber.d(illegalAccess, "Illegal access of FlowManager");
        }

        FlowManager.init(context);

        if (exists(context)) {
            Timber.v("Database exists after FlowManager.init with reflection hack");
        } else {
            Timber.v("Database does not exist after FlowManager.init with reflection hack");
        }
    }
```

**Comment by kaeawc** [comment]
Updated merge conflicts

**Comment by setiawanp** [comment]
@agrosner: Any update regarding this PR? The bug really annoys me. `FlowManager#destroy` is very useful. On the other hand, the bug make it pointless if the user should close the app first before the app could create a new database. Hope this could be merged soon.

**Comment by franzejr** [comment]
@kaeawc this hack worked perfectly for me. Thanks! Looking forward to  see this bug be fixed in the next version!

**Pull request merged**
