### PR TITLE
Make AsyncModel constructor public to allow custom Model implementations

### PR DESCRIPTION
**Pull request by panzerfahrer**

### CODE REVIEW

**Comment by mlebarron** [comment]
@panzerfahrer is there a specific need for this? or just a general allowance?

**Comment by panzerfahrer** [comment]
Basically there are two reasons:
1. my initial model class hierarchy didn't allow me to subclass `BaseModel` in a reasonable way.
2. my unit tests were failing because in `BaseModel` the `ModelAdapter` gets initialized in the constructor (tests use test classes subclasses abstract classes, thus there is no database defined for those).

Additionally, since the `Model` interface is public, I feel the `AsyncModel` should also be fully accessible to allow custom implementations with similar features as provided by `BaseModel` or other library classes.

**Comment by agrosner** [comment]
@panzerfahrer The reason the constructor is not public is to force you to call `.async()` method, which returns the `Async` version of the object. There is no need to use the constructor for the object.

**Comment by agrosner** [comment]
I believe as of `2.2.1`, the `ModelAdapter` is not initialized until an operation on the `Model` class occurs.

**Comment by panzerfahrer** [comment]
@agrosner please don't miss my first point: I can't subclass `BaseModel`. I implemented the `Model` interface and the `async()` method.

With the `AsyncModel` constructor not being accessible, I would need to re-implement everything from `AsyncModel`, wouldn't I?

**Comment by panzerfahrer** [comment]
Waiting for response/clarification. Also, let me know if the latest conflicts should be resolved.

**Comment by agrosner** [comment]
async model is now public, closing.

**Pull request closed without merging**
