### PR TITLE
Custom script migration

### PR DESCRIPTION
**Pull request by carmas123**
Custom script migration

### CODE REVIEW

**Comment by agrosner** [comment]
so what kind of problem is these changes trying to solve? just curious. Can you explain. thank you

**Comment by carmas123** [comment]
So, thank you for your reply.
I want to implement a db migration stepped with SQL Script 1.sql, 2.sql, etc...
but without automatic model creation, all with SQL Script.

**Comment by carmas123** [comment]
and to do all SQL Script without conflict (like triggers with multiple instructions) we need to add a custom script separator.

**Comment by carmas123** [comment]
@agrosner please can you add this functionality...it doesn't have any conflicts with your version and can be useful for me.

**Comment by carmas123** [comment]
Solved with a Custom OpenHelperCreator.
You can close it. :) thank you

**Pull request closed without merging**
