### PR TITLE
Fix TypeConverter

### PR DESCRIPTION
**Pull request by obuiron**
Fix TypeConverters to allow query based on subclass's instance. (see GregorianCalendar with CalendarTypeConverters).
Related issue : https://github.com/Raizlabs/DBFlow/issues/1008

### CODE REVIEW

**Comment by trevjonez** [comment]
This seems rather hacky. Wouldn't it be better to just register the same type converter into the map by an additional class literal key?

**Comment by obuiron** [comment]
I don't think your proposition is suitable, cause it's mean to literaly define the allowed subclass invalidate the idea of create a type converter based on superclass.

Example : 
I define a converter for Vehicle superclass this mean I need to change definition for each future subclasses (Car, Train, ...).

[Type converter](https://github.com/Raizlabs/DBFlow/blob/master/usage2/TypeConverters.md) have been designed to be easy to create and use why add more complexity ?

**Comment by trevjonez** [comment]
I am not proposing you define a new converter for every type. I think that it should just be possible to expose a converter mapping method on the `FlowConfig.Builder` class.

something like:
```java
<Subtype> Builder allowSubtypeConversion(Class<Subtype> subType, Class<? super SubType> superType);
```

you could then specify explicitly:
```java
new FlowConfig.Builder(this)
        .addDatabaseHolder(MySampleGeneratedDatabaseHolder.class)
        .allowSubtypeConversion(GregorianCalendar.class, Calendar.class)
        .openDatabaseOnInit(true)
        .build()
```

Where the call to `allowSubtypeConversion` would fail if there is not a converter for type Calendar.

This would require that the consuming code explicitly request the behaviour rather than the behaviour being present even when it may not be desirable. These types of implicit behaviors can frequently lead to hard to track down subtle bugs.

This fix fails when the inheritance is more that one level deep.

`PinkTintedRed -> Red -> Color` if the converter is for type `Color` it won't find it for `PinkTintedRed`

This fix also fails when the super type is an interface which is where something like this may be really helpful.

**Comment by obuiron** [comment]
I understand what you mean and I'm agree of interfaces and deeper inheritance is missing and might be helpful.

I'll look for another implementation.

May be at TypeConverter annotation, processor will add converters in generated DatabaseHolder.

Converter : 
```
@com.raizlabs.android.dbflow.annotation.TypeConverter(allowedSubTypes = {GregorianCalendar.class})
public class CalendarConverter extends TypeConverter<Long, Calendar> {
...
}
```

GeneratedDatabaseHolder : 
```
public final class GeneratedDatabaseHolder extends DatabaseHolder {
  public GeneratedDatabaseHolder() {
    ...
    typeConverters.put(Calendar.class, new CalendarConverter());
    typeConverters.put(GregorianCalendar.class, new CalendarConverter());
    ...
  }
}
```

**Comment by agrosner** [comment]
closing this in favor of a `allowedSubtypes` solution.

**Pull request closed without merging**
