### PR TITLE
Rx2 extension: Issue with incorrect emitting data in the RXSQLite.rx(...) -> RXModelQueriableImpl.queryStreamResults()

### PR DESCRIPTION
**Pull request by ultraon**
The calling CursorResultFlowable.CursorResultObserver.disposable.isDisposed() returns true all the time.

Explanation:
In the CursorResultFlowable.CursorResultObserver the Disposable object is always disposed because it is created by SingleFromCallable when calling RXModelQueriableImpl.queryResults().  The SingleFromCallable.subscribeActual(SingleObserver) calls singleObserver.onSubscribe(EmptyDisposable.INSTANCE) wich is in state disposed befor callin singleObserver.onSuccess(v). In our case the singleObserver is CursorResultObserver (nestet class of the CursorResultFlowable).

### CODE REVIEW

**Comment by bdesemb** [comment]
Please resolve conflict ASAP. I had the same issue on 4.0.2. My code was very simple:
```
return RXSQLite.rx(SQLite
                .select()
                .from(SalesResto.class))
                .queryStreamResults()
```
I tried your fix and it worked perfectly.

**Comment by ultraon** [comment]
In my latest changes i've fixed bug with RxJava2 contract while using Single<Void> and execution Callable that returns null (should throws NoSuchElementException, see https://github.com/ReactiveX/RxJava/issues/5404#issuecomment-307395927 ).

**Comment by agrosner** [comment]
@ultraon please address my comments. it would be great to get this in!

**Comment by ultraon** [comment]
@agrosner I've resolved conflicts. Unfortunately i didn't see your comments to my PR.

**Comment by iveyalkin** [comment]
It would be nice to have `Maybe` returned along with/instead of a `Single`. 👍

**Comment by agrosner** [comment]
will close as comments not addressed. thank you.

**Comment by ultraon** [comment]
But you didn't add any comments for my PR!

**Comment by agrosner** [comment]
yes up at the top are review comments. 
screen shot 2017-12-28 at 1 10 46 pm

**Comment by ultraon** [comment]
@agrosner Thank you for screenshot, i really didn't see your comment because i think you forgot to click "Start a review" button, and your comment was in state "Pending" (in this state only you can see your comment), for details see [doc](https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/) item Num 5. 
Could you please also tell me, did you make any proposed changes for Rx2 module?

**Pull request closed without merging**
