### PR TITLE
Fixed #925

### LINKED ISSUE #925: No way to reopen closed database
DBFlow Version: 3.1.1
Issue Kind : Bug
Description: 

`FlowSQLiteOpenHelper#getDatabase` always return same `SQLiteDatabase`. I think `FlowSQLiteOpenHelper#getDatabase` should work like `SQLiteOpenHelper#getWritableDatabase`: if the database is closed it will create new database instead.

### PR DESCRIPTION
**Pull request by douo**
See [#925](https://github.com/Raizlabs/DBFlow/issues/925)

### CODE REVIEW

**Comment by saschpe** [comment]
rebase?

**Comment by douo** [comment]
It make `FlowSQLiteOpenHelper` reusable after closed the internal `SQLiteDatabase`

**Comment by agrosner** [comment]
this in `4.0.0-beta3`.

**Comment by jermainedilao** [comment]
@agrosner hi, im using 3.1.1 and experiencing this issue too. Is it required to update to 4.0.0-beta3 to have this fix?

**Pull request closed without merging**
