### PR TITLE
Allow passing selectionArgs to queries.

### PR DESCRIPTION
**Pull request by GrahamRogers**
Added selectionArgs to methods that execute queries to allow having ? placeholders in queries.

### CODE REVIEW

**Comment by agrosner** [comment]
I appreciate the work that you've done on this, however I don't think adding a varg to every `ModelQueriable` method is the cleanest way to do this. Also, the whole point of the SQL-wrapper language is to eliminate the need for this. What would the use-case for this be?

**Comment by GrahamRogers** [comment]
I'd like to create pre-compiled SQL statements to avoid having to create them multiple times. This is the recommended pattern in Android since it prevents having to create objects unnecessarily.

**Comment by GrahamRogers** [comment]
I actually originally started doing this to implement https://github.com/Raizlabs/DBFlow/pull/612, but it turns out this isn't necessary for that. I don't mind if this pull request gets dropped, but I there are valid cases where you want to cache the query for efficiency. Perhaps just keep the isSelectionArg and isNotSelectionArg methods, then the user can use the String produced by getQuery()?

**Comment by agrosner** [comment]
I added a `compileStatement()` method at the end of a query, such that:
```
DatabaseStatement statement = SQLite.select().from(MyTable.class).where(...).compileStatement();
```

**Pull request closed without merging**
