### PR TITLE
Loaders and cursors for DBFlow

### PR DESCRIPTION
**Pull request by hilljh82**
This pull request contains the implementation of the following classes to improve Loader support for DBFlow.
- `FlowCursorAdapter`: The purpose of this class is to improve support for `CursorAdapter`. In particular, we overload the `getItem (position)` method to return the actual model element at that position instead of a `Cursor`. 
- `FlowSimpleCursorAdapter`: This class allows the `SimpleCursorAdapter` to easily support DBFlow. Similar to `FlowCursorAdapter`, we overload the `getItem(position)` method to return a model element, instead of a `Cursor`.
- `FlowCursorLoader`: This class integrates DBFLow with the Android `Loader` framework. In particular, the loader must be created with a `Queriable` object. The `Queriable` object is used by the loader to load models. The end result of this loader is a Cursor that can be used like the cursor returned by `CursorLoader`. A key feature of this loader is the ability to leverage the model observer framework in DBFlow via the `(un)registerForContentChanges()` methods. Using this methods will configure the loader to observe changes to models of interest. Any change observed will trigger the loader to automatically reload. This simplifies storing data in the database via DBFlow models, and updating corresponding views as a result of the storage updates.
- `FlowSingleModelLoader`: This is the base class for the following single model classes: `FlowModelLoader`, `FlowModelViewLoader`, `FlowModelQueryLoader`. Single model loaders are for queries that return 1 model, not a list of models or a cursor to a list of models. We treat these different from the list loaders because we need to appropriate `InstanceAdapter` to create the single model, and load it from the cursor. The result of each load is a single, usable model. Similar to the `FlowModelLoader`, these loaders will automatically reload if the underlying table changes. Also, you can register for updates to models that have nothing to do with the final model. This is of interest when dealing with query models since the final model may be the composition of data from many different tables.

Lastly, each loader has been tested in applications that I am currently using. It would be great if these classes can be incorporated into the next release of DBFlow.

### CODE REVIEW

**Comment by agrosner** [comment]
Im going on vacation starting tomorrow for two weeks, so I dont have much time to look this over until later this month. A few things high level:
1. Match code style with rest of lib. I noticed that braces were on different lines, spacing, and other were not matching rest of lib.
2. Why is this PR adding travis CI? It seems like it should go in a separate PR.
3. What is `ExternalForeignKey`? This belongs in a new PR
4. Version for new features should go up a middle . so it should be *3.2.0* not *3.1.1*

**Comment by agrosner** [comment]
For `FlowCursorAdapter` you know we have `FlowCursorList`? which essentially replaces `CursorAdapter`. Just wrap your regular adapter with the list inside of it and should map nicely.

**Comment by hilljh82** [comment]
@agrosner The Travis CI should not be in this pull-request. The problem is that I pushed it to the develop branch instead of its own branch. Since this pull-request has been outstanding for some time, it was automatically included when I just did the push today for working with Travis CI.

I will make the necessary code style changes.

In regards to `FlowCursorList`, I am aware of it. Although `FlowCursorList` works, it's not a `CursorAdapter`. By the nature of the inheritance structure, `FlowCursorAdapter` is a `CursorAdapter`. Using `FlowCursorList` still requires the developer to write their own Adapter (from what I have seen/used) that integrates the cursor with the adapter. Please correct me if I'm wrong.

The `FlowCursorAdapter` does not. If you want to add all the caching support as in `FlowCursorList`, then I recommend subclassing from `FlowCursorAdapter` with a class named `CacheFlowCursorAdapter` (or something). This way, the developer has the option of using caching or not, and it is not forced upon them.

**Comment by hilljh82** [comment]
@agrosner If you are using Android Studio, or any JetBrains, product to work on DBFlow, can you please export your coding style and commit them to the database? This way, we can import them as a style, and use then when working on DBFlow? This will save a lot of time and effort reviewing and fixing coding styles.

**Comment by hilljh82** [comment]
@agrosner The pull-request should be ready to go now.

**Comment by hilljh82** [comment]
@agrosner Any update on when this pull-request will be accepted?

**Comment by hannesa2** [comment]
@agrosner Any update on if/when this pull-request will be accepted?

**Comment by hilljh82** [comment]
@agrosner I fixed the conflicts for this PR related to the latest updates on the develop branch. I also fixed the `ExternalForeignKey` build error that I did not realize was present. I hope this resolves the issues so the PR can be merged.

**Comment by hilljh82** [comment]
@agrosner Still fixing the conflicts related to the latest updates to the develop branch.

**Comment by hilljh82** [comment]
@agrosner I have fixed the conflicts that prevented auto-merging of this PR. I also realized there was a left over reference to `ExternalForeignKey` that I have also removed.

**Comment by hilljh82** [comment]
@agrosner I am going to close this PR, and open a new once since there seems to be some more issues related to merge conflicts.

**Comment by hilljh82** [comment]
This PR has been re-issued under #1091.

**Pull request closed without merging**
