### PR TITLE
Fixed bug #448: Adding new column of type Date during migration makes the app to crash.

### PR DESCRIPTION
**Pull request by AntonioCappiello**
Issue description: https://github.com/Raizlabs/DBFlow/issues/448

### CODE REVIEW

**Comment by AntonioCappiello** [comment]
Dear @agrosner, could you please review my PR? Thanks in advance.

**Comment by AntonioCappiello** [comment]
Dear @agrosner could you please review my PR?

**Comment by AntonioCappiello** [comment]
The type **Date** is not part of the enumerator **SQLiteType** and of its relative HashMap, which causes the migration to fail anytime that we want to add a column with the **Date** type.
The issue is still open.

**Comment by agrosner** [comment]
we don't use `Date` as a type of column, rather its converted via a built-in `TypeConverter`. It uses `Long` as it's column type, so if you need to migrate that column, use the `SQLiteType.INTEGER` value. If you want, you can use a custom `TypeConverter` on a specific DB column, in that case you would still have to use the `SQLiteType` to add it. closing.

**Pull request closed without merging**
