### PR TITLE
Fix broken IndexMigration

### PR DESCRIPTION
**Pull request by saschpe**
Properly use the getName() method that subclasses have the implement.
No need to keep a 'name' member around for this purpose. Re-enable
previously broken test.

### CODE REVIEW

**Comment by agrosner** [comment]
@saschpe can you update just the one file (MigrationTest) that has conflict. All test classes moved to Kotlin, so if you could make that change in the kotlin file and push that would be great :)

**Comment by saschpe** [comment]
@agrosner done

**Comment by saschpe** [comment]
Rebased once more

**Comment by agrosner** [comment]
sorry I didnt see this fixed.

**Pull request merged**
