### PR TITLE
Optionally Configure Table Alias in @Table

### PR DESCRIPTION
**Pull request by danvwells**
We have a lot of queries that do a lot of joining.  To remove any ambiguity between columns, especially id columns, we always use withTable() on each property and as() for each table.  To shorten the generated SQL we see in our logs, we pass a NameAlias to withTable() and as().  This ends up cluttering our code quite a bit, so this PR makes it so we can optionally add a table alias in the @Table configuration that would get used in all queries, etc.  It can of course still be overridden case by case using the withTable() and as() functions.  If it is not provided in @Table, then it's business as usual.

Thoughts @agrosner?

### CODE REVIEW

**Comment by danvwells** [comment]
Just following up @agrosner on this and the other 2 or 3 PRs I submitted.  Thanks

**Comment by agrosner** [comment]
thanks for your PR. I think this might be not needed. I mean you can just write a Kotlin extension function that does what you need:
```kotlin
fun From<MyTable>.fromMyAlias() = from(MyTable::class.java).as("SomeAlias")
```
And then in queries:
```kotlin
val list = select.fromMyAlias() where ...
```

or if you're in Java, just write a utility method that wraps the select from:
```java

public static From<MyTable> selectAliasFromMyTable() {
  return SQLite.select().from(MyTable.class).as("MyAlias");
}

```

**Comment by danvwells** [comment]
Thanks for looking at it!  Yes, utility/extension methods can be written, which we do in various cases, but I think this PR makes it more flexible and requires the user of this library to write less code.  Especially in complex joins, I think this is pretty nice and let's you focus on the actual query.  Do you have any concerns with the change?  Thanks again for your consideration, and for DBFlow!

**Comment by danvwells** [comment]
Consider this java example joining 3 tables: 

```Java
String firstAlias = "fa";
NameAlias first = NameAlias.of(firstAlias);
String secondAlias = "sa";
NameAlias second = NameAlias.of(secondAlias);
String thirdAlias = "ta";
NameAlias third = NameAlias.of(thirdAlias);

SQLite.select(
    First_Table.someProperty.withTable(first), 
    Second_Table.someProperty.withTable(second), 
    Third_Table.someProperty.withTable(third)
)
.from(First.class).as(firstAlias)
.join(Second.class).as(secondAlias)
    .on(First_Table.secondId.withTable(first).eq(Second_Table.id.withTable(second))
.join(Third.class).as(thirdAlias)
    .on(Second_Table.thirdId.withTable(second).eq(Third_Table.id.withTable(third)))
```

Each property in the projection comes from a different table.  I could have many different queries joining these and other tables, projecting different columns, or whatever.  Note the ```withTable()``` calls on each property in the projection as well as in the joins.  Also note the ```as()``` calls on each table.  All of this goes away with the model's ```@Table``` annotation including the tableAlias parameter from this PR.  I'm not sure how I could have a utility method do this that I could write once and use everywhere.

So the above becomes:
```java
@Table(database = MyDatabase::class, tableAlias = "fa")
class First {
 // same setup for Second and Third classes
...

SQLite.select(
    First_Table.someProperty,
    Second_Table.someProperty,
    Third_Table.someProperty
)
.from(First.class).
.join(Second.class)
    .on(First_Table.secondId.eq(Second_Table.id)
.join(Third.class)
    .on(Second_Table.thirdId.eq(Third_Table.id))
```

I hope that makes sense.  Thanks again for taking a look.

**Comment by agrosner** [comment]
1. you can use the `name` attribute on the `@Table` object if the class name is not what you wanted originally.  Use an `AlterTableMigration`, rename table, and then keep it as intended. 
2. make static method that returns the proper alias or kotlin extension.

It really just offloads the work to the annotation processor, and by using a general alias, you have to understand that immediately that an alias for table is used, thus if you wanted original table name, you will have to `.as("tableName")` on all of them anyways if you're not careful.

**Comment by danvwells** [comment]
1.  Sorry, I don't understand how renaming the table is related.  The alias here is to prevent column ambiguity.
2.  Your example static method / kotlin extension functions don't solve generically or flexibly what this PR is solving, but they do give me an idea.  Perhaps I can wrap the dbflow wrapper language with my own versions of select(), from(), join(), on(), etc that always qualifies using the table name.  Seems it would be a nice feature to have built-in, but perhaps that would work for us.

Yes, it does offload the work to the annotation processor, which is intended.  Less work for coder.  Yes, if tableAlias is used, the coder must be aware of that, and one could argue it may not be so obvious, which is why I made it optional and it is not used by default, but I can see the argument there.

Thanks again for your consideration.

**Comment by agrosner** [comment]
ah for 1. you mean just prefixing alias so it always contain something unique in a query between multiple columns? yeah I can do that. its a breaking change, which I can introduce in 5.0 to always include table prefix in queries so that an alias is not necessary. 
2. Yeah makes sense now that I understand it more. I think by doing (1) adding table prefix to all generated `Property` objects, this issue will go away

what do you think?

**Comment by agrosner** [comment]
so a normal property say `@Column var name: String? = null` will generate a property that represents itself by default as `MyTable.name` in SQLite translation?

**Comment by danvwells** [comment]
Yes, I think that could work.  I was using aliases so the SQL in our logging doesn't get too crazy to read - some table names are a little long.  We log all sql in debug builds.  So personally, I'd still like to configure an alias in one place.

Also, why is your thought a breaking change again?

**Pull request closed without merging**
