### PR TITLE
Remove columns migration

### PR DESCRIPTION
**Pull request by hilljh82**
This pull-request is for a migration to remove columns from a table. 

SQLite does not support removing columns from a table via ALTER TABLE. Instead, you must copy the data to a backup table, create a new table with fewer columns, and copy the data from the backup table to the new table with fewer columns. The `RemoveColumnsMigration` codifies this pattern. The only requirement for the developer when using `RemoveColumnsMigration` is define a backup model, which subclasses the original model. The backup model then contains the columns to be removed from the original model.

Here is how one would use `RemoveColumnsMigration`:

```java
// UserProfile.java
@Model(database = MigrationDatabase.class)
public class UserProfile extends BaseModel {
    @Column
    public String firstName;

    @Column
    public String lastName;
}

// UserProfileBackup.java
@Model(database = MigrationDatabase.class)
public class UserProfileBackup extends UserProfile {
    @Column
    public String dropColumn;
}
```
 
Then, define the migration to remove the columns:

```java
@Migration(version = 2, database = MigrationDatabase.class)
public static class RemoveColumnsFromUserProfile extends RemoveColumnsMigration<UserProfile, UserProfileBackup> {
    public RemoveColumnsFromUserProfile () {
      super (UserProfile.class, UserProfileBackup.class);
    }
}
```

In the end, `dropColumn` will be removed from the `UserProfile` table in the
database.

The usage of `RemoveColumnsMigration` has been documented in `Migrations.md`.

### CODE REVIEW

**Comment by trevjonez** [comment]
The problem with this is it assumes that `UserProfile` doesn't change in the future.

If I add a column in migration three, this migration two breaks it, when running a migration from version 1 -> 3. In this situation the migration code is now trying to run based on the version three adapter creation query. When migration three goes to perform a simple add column it will fail because the column already exists.

The same story will play true with most any other alteration to `UserProfile`.

**Comment by hilljh82** [comment]
Any suggestions on improvements to handle this situation. Also, this is not meant to handle complex cases—just the basics.

**Comment by trevjonez** [comment]
Personally I feel like migrations should always be written out rather than calculated at run time, so as to implicitly encode both the "from" and "to" schema thus ensuring that they don't have side effect on later migrations.

It might be possible to write a bit of annotation processing code to generate the migration for you but the issue is that without the version one backup table you are going from an unknown state. That backup table is wasteful in terms of maintenance and method count.

Just seems to me that while a manually written out migration can take some time to write it is just far safer and less expensive in the long run than some dynamic solutions.

Have you tried doing the migration in an SQL file? They tend to be less tedious since they are written directly in SQL. So long as you avoid migrations that have things that would break later migrations you should be fine. And write tests for all migration paths. `1` -> `N` .... `N-1` -> `N`

**Comment by agrosner** [comment]
I think this approach as @trevjonez has said leaves the backup table there. Also it definitely is safer to write out on your own. A manual approach, while not ideal would keep this very safe and ensure that the backup table class somehow doesnt change. I think theres a way to do this to ensure safely.

**Pull request closed without merging**
